stages:
  - build
  - release
  - deploy

build:
  stage: build
  image: node:18
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

variables:
  CONTAINER_IMAGE: $CI_REGISTRY_IMAGE:latest

release-job:
  services:
    - docker:dind
  stage: release
  image: docker:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
  script:
    - docker build -t $CONTAINER_IMAGE .
    - docker push $CONTAINER_IMAGE
  after_script:
    - docker logout
  retry:
    max: 2
    when:
      - always

deploy:
  services:
    - docker:dind
  stage: deploy
  image: docker:latest
  before_script:
    - chmod 400 $SSH_KEY
  script:
    - ssh -o StrictHostKeyChecking=no -i $SSH_KEY -p 69 $SERVER_USER@$SERVER_IP "
      docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
      cd /applications/maceioin &&
      docker pull $CONTAINER_IMAGE &&
      docker compose down &&
      docker compose up -d"